# version: '3'
# services:
#   sim:
#     image: f1tenth_gym_ros
#     build: ./f1tenth_gym_ros/
#     volumes: 
#       - ./f1tenth_gym_ros:/sim_ws/src/f1tenth_gym_ros
#       - /tmp/.X11-unix:/tmp/.X11-unix 
#       - ./f1tenth_rl:/sim_ws/src/f1tenth_rl
#     environment:
#       - DISPLAY=$DISPLAY
#     networks:
#       - x11
#     stdin_open: true
#     tty: true 

# networks:
#   x11:

version: '3'
services:
  sim:
    image: f1tenth_gym_ros
    build: ./f1tenth_gym_ros/
    volumes:
      - ./f1tenth_gym_ros:/sim_ws/src/f1tenth_gym_ros
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./f1tenth_rl:/sim_ws/src/f1tenth_rl
    environment:
      - DISPLAY=$DISPLAY
    network_mode: "host"
    stdin_open: true
    tty: true
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]